name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.*
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish -f net5.0 -c Release -o ./Release -r win-x64 --self-contained false
    - name: FTP Deploy        
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        host: ftp.ph105.peopleshostshared.com
        user: artizans
        password: Yidh&X1&4N32mP
        localDir: "./Release"
        remoteDir: "/httpdocs"
        options: "--delete"
